name: Resume CI Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Build the Docker image with version tag
      run: docker build . --file Dockerfile --tag my-image-name:${{ github.run_number }}

    - name: Build Docker image with 'latest' tag
      run: docker build . --file Dockerfile --tag my-image-name:latest

    - name: Login to Docker Hub
      run: docker login -u ${{ secrets.REGISTRY_USERNAME }} -p ${{ secrets.REGISTRY_PASS }}

    - name: Tag image for Docker Hub
      run: docker tag my-image-name:${{ github.run_number }} ${{ secrets.REGISTRY_USERNAME }}/my-image-name:${{ github.run_number }}

    - name: Push image to Docker Hub
      run: docker push ${{ secrets.REGISTRY_USERNAME }}/my-image-name:${{ github.run_number }}
